server:
  #address: localhost
  port: 8080
  display-name: Area - Indonesia by GO Indonesia
  server-header: GO Indonesia
  compression:
    enabled: true
  undertow:
    accesslog:
      enabled: true
  tomcat:
    accesslog:
      enabled: true
    uri-encoding: UTF-8
spring:
  profiles:
    active: development
  session:
    store-type: jdbc
  datasource:
    url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
    dbcp2:
      test-while-idle: true
      validation-query: SELECT 1
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate:
        search:
          default:
            directory_provider: filesystem
            indexBase: ${user.home}/.lucene/area-indonesia/indexes/
#flyway:
#  enabled: true
#  url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#  user: sa
#  password:
logging:
  level: error
  file: ${user.home}/.log/area-indonesia/application.log