version: 2
jobs:
  build:
    docker:
      - image: lwieske/java-8:server-jre-8u121-slim
        environment:
          PROD_VERSION: 1.0
    steps:
      - checkout
      - run:
          name: Building
          command: gradle build
      - run:
          name: Jacoco Report
          command: ./gradlew jacocoTestReport
      - run:
          name: Codecov Report
          command: bash <(curl -s https://codecov.io/bash) -t ef57bb57-a458-4a0d-a5b1-ca5639d6d3f7
